app-name: roster # roster
initials: ms # ms
language: gradle

github-app-repo-uri: "git@github.com:msjobakk/roster.git"

github-pipelines-repo-uri: "git@github.com:msjobakk/training-pipelines.git"

cf-dev-api: https://api.run.pivotal.io # set to cf api endpoint
cf-dev-org: rscale-training-3
cf-dev-space: mike
cf-dev-hostname: roster-msjobakken # set to '<app-name>-<first_initial><lastname>'. ex: roster-sgreenberg
cf-dev-domain: cfapps.io # set to the apps domain for your CF
cf-dev-manifest: dev-manifest.yml # set to the dev manifest path in your app repository. ex: dev-manifest.yml
